### ISSUE TITLE
Wrong date on events when user is in different timezone

### ISSUE THREAD

**Issue by kuzdogan** [blockchainweek/explore#6]
People are reporting they see different dates for the events in different timezones. 

https://github.com/blockchainweek/data/issues/65#issuecomment-2099179524
https://github.com/blockchainweek/data/issues/47#issuecomment-2096689159
https://github.com/blockchainweek/data/issues/49#issuecomment-2099143380

I tried to debug the issue and was able to reproduce it with a [timezone spoofer](https://chromewebstore.google.com/detail/spoof-timezone/kcabmhnajflfolhelachlflngdbfhboe?hl=de) on my browser. The weird things is, the date initially shows correct then in a eye-blink it changes to the wrong date. However I wasn't able to catch the `formatItemDate` function or other formatters running twice. They only give `console.log` outputs once. Maybe that's about something I don't know about how Svelte works.

This happens on each refresh. I am refreshing in the video below.

https://github.com/blockchainweek/explore/assets/13069972/e3e92f87-8905-47ea-82d8-41b0e7853af5

I was able to track down the issue into the `format` function of the `date-fns`. The input to it is the non-timezoned date but it spits out the date in the timezone of the browser. And even in some examples it made the timezone `+`s to `-`s and vice-versa.

Take this code snippet I tried for example:
```js
export function formatItemDate(item, opts = {}) {
	console.log(item.name);
	console.log(item.date);
	// Directly parse the ISO string into a date object with parseISO
	let dt = parseISO(item.date + 'T00:00:00'); // Add time to ensure it's the start of the day

	console.log('dt: ' + dt);
	let formattedDate = format(
		dt,
		'MMMM d hh:mm a O' + (opts.full && item.days === 1 ? ', yyyy' : '')
	);

	console.log('formattedDate: ' + formattedDate);
	if (item.days > 1) {
		let endDate = addDays(dt, item.days - 1);
		formattedDate += '-' + format(endDate, 'd' + (opts.full ? ', yyyy' : ''));
	}

	return formattedDate;
}
```

This is the output of this function call with `item = { date: "2024-05-22", name: "Web3privacy now meetup"}`

```
Web3privacy now meetup
2024-05-22
dt: Wed May 22 2024 00:00:00 GMT-0400 (Eastern Daylight Time)
formattedDate: May 21 11:00 PM GMT+4
```

**Comment by burningtree** [comment]
> The weird things is, the date initially shows correct then in a eye-blink it changes to the wrong date.

@kuzdogan This is because of SSG (Static Site Generation) or SSR (Server-Side generation). The correct timezone is probably set on the server, so it is generated correctly - but since the client has a different timezone, it is immediately swapped with the client-side date after hydration.

The solution is to make sure that the dates are consistent across server and client.

In the case of the snippet above, it is to use ISO Date which has a specified timezone. That is:

Instead of this:
```js
let dt = parseISO(item.date + 'T00:00:00');
```

use this:
```js
let dt = parseISO(item.date + 'T00:00:00Z');
```

The "Z" at the end guarantees that the date will always have the same timezone (Z = UTC+0).

**Comment by burningtree** [comment]
Unfortunately this is something that hasn't been resolved in the original Explorer by PBW.

As a systematic solution I suggest:
1. add a `timezone` flag to each year in the data repository - this will serve as a reference timezone, in this case "Europe/Berlin"
2. in explorer, load the date in the correct timezone via `dateFnsTz.fromZonedTime()` (according to the flag)
3. in the interface then display the dates via `dateFnsTz.formatInTimeZone()` (i recommend to show in Europe/Berlin) instead of via `dateFns.format()`

The whole principle is that the source data is relative (no timezone) - so we need to convert it to absolute form (ideally to Z (UTC+0)), and then display it again in relative form.

https://github.com/marnusw/date-fns-tz

EDIT: I see there is already variable `tz` in config.js - so that can be used instead (1)
https://github.com/blockchainweek/explore/blob/d6ac895d5fc3891b7eb9e19d96592690a18cf830/src/lib/bbw.js#L2

**Comment by kuzdogan** [comment]
Fixed with https://github.com/blockchainweek/explore/commit/46a9082e8da069a76ba2bf10929e7b5728a55223 

However using the `formatInTimeZone` function in the TimelineHeatmap breaks the build. I can build locally (M1 Pro Mac) but the Github Ubuntu builds hang indefinitely https://github.com/blockchainweek/explore/actions/runs/9022033526

Anyways turns out `formatInTimeZone` in TimelineHeatmap is not required according to what users with the issues are reporting

https://github.com/blockchainweek/data/issues/47#issuecomment-2102855853
https://github.com/blockchainweek/data/issues/65#issuecomment-2102704078
